### ISSUE TITLE
Occasional but inconsistent connection timeouts result in "parsing errors"

### ISSUE THREAD

**Issue by dchan3** [OpenHRS/openhrs-scraper-app#10]
This issue is important because we lose data as a result of this occurring.
I have attached a screenshot of my terminal output for reference. I would advise against scraping at low speeds.
<img width="1277" alt="screen shot 2017-10-18 at 11 05 18 am" src="https://user-images.githubusercontent.com/11368560/31742764-655e263e-b3f4-11e7-8ad6-b44e3b6835a5.png">

**Comment by terrypalo** [comment]
A work around could be to make a function to keep trying until it works. Will need to look more into it

**Comment by dchan3** [comment]
Closing issue because of changes in #15. You will need to terminate the process in a different manner because of the loop I made.
